// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_nodeagent_baremetalmachine.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BareMetalMachineRequest struct {
	BareMetalMachines    []*BareMetalMachine `protobuf:"bytes,1,rep,name=BareMetalMachines,proto3" json:"BareMetalMachines,omitempty"`
	OperationType        common.Operation    `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BareMetalMachineRequest) Reset()         { *m = BareMetalMachineRequest{} }
func (m *BareMetalMachineRequest) String() string { return proto.CompactTextString(m) }
func (*BareMetalMachineRequest) ProtoMessage()    {}
func (*BareMetalMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd8056a59881a07, []int{0}
}

func (m *BareMetalMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BareMetalMachineRequest.Unmarshal(m, b)
}
func (m *BareMetalMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BareMetalMachineRequest.Marshal(b, m, deterministic)
}
func (m *BareMetalMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BareMetalMachineRequest.Merge(m, src)
}
func (m *BareMetalMachineRequest) XXX_Size() int {
	return xxx_messageInfo_BareMetalMachineRequest.Size(m)
}
func (m *BareMetalMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BareMetalMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BareMetalMachineRequest proto.InternalMessageInfo

func (m *BareMetalMachineRequest) GetBareMetalMachines() []*BareMetalMachine {
	if m != nil {
		return m.BareMetalMachines
	}
	return nil
}

func (m *BareMetalMachineRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type BareMetalMachineResponse struct {
	BareMetalMachines    []*BareMetalMachine `protobuf:"bytes,1,rep,name=BareMetalMachines,proto3" json:"BareMetalMachines,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BareMetalMachineResponse) Reset()         { *m = BareMetalMachineResponse{} }
func (m *BareMetalMachineResponse) String() string { return proto.CompactTextString(m) }
func (*BareMetalMachineResponse) ProtoMessage()    {}
func (*BareMetalMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd8056a59881a07, []int{1}
}

func (m *BareMetalMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BareMetalMachineResponse.Unmarshal(m, b)
}
func (m *BareMetalMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BareMetalMachineResponse.Marshal(b, m, deterministic)
}
func (m *BareMetalMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BareMetalMachineResponse.Merge(m, src)
}
func (m *BareMetalMachineResponse) XXX_Size() int {
	return xxx_messageInfo_BareMetalMachineResponse.Size(m)
}
func (m *BareMetalMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BareMetalMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BareMetalMachineResponse proto.InternalMessageInfo

func (m *BareMetalMachineResponse) GetBareMetalMachines() []*BareMetalMachine {
	if m != nil {
		return m.BareMetalMachines
	}
	return nil
}

func (m *BareMetalMachineResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *BareMetalMachineResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BareMetalMachineOperatingSystemConfiguration struct {
	ComputerName         string               `protobuf:"bytes,1,opt,name=computerName,proto3" json:"computerName,omitempty"`
	Administrator        *UserConfiguration   `protobuf:"bytes,2,opt,name=administrator,proto3" json:"administrator,omitempty"`
	Users                []*UserConfiguration `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	CustomData           string               `protobuf:"bytes,4,opt,name=customData,proto3" json:"customData,omitempty"`
	PublicKeys           []*SSHPublicKey      `protobuf:"bytes,5,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	LinuxConfiguration   *LinuxConfiguration  `protobuf:"bytes,6,opt,name=linuxConfiguration,proto3" json:"linuxConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BareMetalMachineOperatingSystemConfiguration) Reset() {
	*m = BareMetalMachineOperatingSystemConfiguration{}
}
func (m *BareMetalMachineOperatingSystemConfiguration) String() string {
	return proto.CompactTextString(m)
}
func (*BareMetalMachineOperatingSystemConfiguration) ProtoMessage() {}
func (*BareMetalMachineOperatingSystemConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd8056a59881a07, []int{2}
}

func (m *BareMetalMachineOperatingSystemConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BareMetalMachineOperatingSystemConfiguration.Unmarshal(m, b)
}
func (m *BareMetalMachineOperatingSystemConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BareMetalMachineOperatingSystemConfiguration.Marshal(b, m, deterministic)
}
func (m *BareMetalMachineOperatingSystemConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BareMetalMachineOperatingSystemConfiguration.Merge(m, src)
}
func (m *BareMetalMachineOperatingSystemConfiguration) XXX_Size() int {
	return xxx_messageInfo_BareMetalMachineOperatingSystemConfiguration.Size(m)
}
func (m *BareMetalMachineOperatingSystemConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_BareMetalMachineOperatingSystemConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_BareMetalMachineOperatingSystemConfiguration proto.InternalMessageInfo

func (m *BareMetalMachineOperatingSystemConfiguration) GetComputerName() string {
	if m != nil {
		return m.ComputerName
	}
	return ""
}

func (m *BareMetalMachineOperatingSystemConfiguration) GetAdministrator() *UserConfiguration {
	if m != nil {
		return m.Administrator
	}
	return nil
}

func (m *BareMetalMachineOperatingSystemConfiguration) GetUsers() []*UserConfiguration {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BareMetalMachineOperatingSystemConfiguration) GetCustomData() string {
	if m != nil {
		return m.CustomData
	}
	return ""
}

func (m *BareMetalMachineOperatingSystemConfiguration) GetPublicKeys() []*SSHPublicKey {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *BareMetalMachineOperatingSystemConfiguration) GetLinuxConfiguration() *LinuxConfiguration {
	if m != nil {
		return m.LinuxConfiguration
	}
	return nil
}

type BareMetalMachine struct {
	Name                 string                                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                                        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Os                   *BareMetalMachineOperatingSystemConfiguration `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	GroupName            string                                        `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Status               *common.Status                                `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Tags                 *common.Tags                                  `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *BareMetalMachine) Reset()         { *m = BareMetalMachine{} }
func (m *BareMetalMachine) String() string { return proto.CompactTextString(m) }
func (*BareMetalMachine) ProtoMessage()    {}
func (*BareMetalMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd8056a59881a07, []int{3}
}

func (m *BareMetalMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BareMetalMachine.Unmarshal(m, b)
}
func (m *BareMetalMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BareMetalMachine.Marshal(b, m, deterministic)
}
func (m *BareMetalMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BareMetalMachine.Merge(m, src)
}
func (m *BareMetalMachine) XXX_Size() int {
	return xxx_messageInfo_BareMetalMachine.Size(m)
}
func (m *BareMetalMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_BareMetalMachine.DiscardUnknown(m)
}

var xxx_messageInfo_BareMetalMachine proto.InternalMessageInfo

func (m *BareMetalMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BareMetalMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BareMetalMachine) GetOs() *BareMetalMachineOperatingSystemConfiguration {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *BareMetalMachine) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *BareMetalMachine) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BareMetalMachine) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*BareMetalMachineRequest)(nil), "moc.nodeagent.compute.BareMetalMachineRequest")
	proto.RegisterType((*BareMetalMachineResponse)(nil), "moc.nodeagent.compute.BareMetalMachineResponse")
	proto.RegisterType((*BareMetalMachineOperatingSystemConfiguration)(nil), "moc.nodeagent.compute.BareMetalMachineOperatingSystemConfiguration")
	proto.RegisterType((*BareMetalMachine)(nil), "moc.nodeagent.compute.BareMetalMachine")
}

func init() {
	proto.RegisterFile("moc_nodeagent_baremetalmachine.proto", fileDescriptor_2fd8056a59881a07)
}

var fileDescriptor_2fd8056a59881a07 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x9c, 0xb4, 0x91, 0x32, 0xf9, 0x5a, 0xc1, 0x8a, 0xaa, 0x56, 0x80, 0xaa, 0x72, 0x91,
	0x08, 0x12, 0xb2, 0x51, 0xe0, 0x1a, 0x89, 0x16, 0x24, 0x10, 0xb4, 0xa0, 0x4d, 0x8b, 0x04, 0x37,
	0xd5, 0xc6, 0xd9, 0xba, 0xab, 0x7a, 0x77, 0xcc, 0xfe, 0x14, 0x72, 0xcf, 0x93, 0x70, 0xc1, 0x4b,
	0xf0, 0x4c, 0xbc, 0x03, 0xf2, 0xda, 0xfd, 0x71, 0xd2, 0xa0, 0xdc, 0x70, 0x95, 0x78, 0xce, 0x99,
	0x33, 0x67, 0x66, 0x3c, 0x86, 0x07, 0x12, 0xd3, 0x63, 0x85, 0x13, 0xce, 0x32, 0xae, 0xec, 0xf1,
	0x98, 0x69, 0x2e, 0xb9, 0x65, 0xb9, 0x64, 0xe9, 0xa9, 0x50, 0x3c, 0x2e, 0x34, 0x5a, 0x24, 0x1b,
	0x12, 0xd3, 0xf8, 0x92, 0x15, 0xa7, 0x28, 0x0b, 0x67, 0x79, 0xff, 0x6e, 0x86, 0x98, 0xe5, 0x3c,
	0xf1, 0xa4, 0xb1, 0x3b, 0x49, 0xb8, 0x2c, 0xec, 0xb4, 0xca, 0xe9, 0x6f, 0xcd, 0x82, 0x5f, 0x35,
	0x2b, 0x0a, 0xae, 0x4d, 0x8d, 0x6f, 0x96, 0x95, 0x53, 0x94, 0x12, 0x55, 0xfd, 0x73, 0x91, 0xd8,
	0x04, 0xca, 0x4a, 0x0d, 0x3c, 0x6a, 0x5a, 0x3e, 0x17, 0xda, 0xba, 0x19, 0xc3, 0xd1, 0xcf, 0x00,
	0x36, 0x77, 0x99, 0xe6, 0xfb, 0x65, 0x2f, 0xfb, 0x15, 0x44, 0xf9, 0x17, 0xc7, 0x8d, 0x25, 0x47,
	0x70, 0x7b, 0x16, 0x32, 0x61, 0xb0, 0xdd, 0x1e, 0xf4, 0x86, 0x0f, 0xe3, 0x1b, 0x1b, 0x8d, 0xe7,
	0xa4, 0xe6, 0x15, 0xc8, 0x33, 0x58, 0x7b, 0x5f, 0x70, 0xcd, 0xac, 0x40, 0x75, 0x38, 0x2d, 0x78,
	0xd8, 0xda, 0x0e, 0x06, 0xeb, 0xc3, 0x75, 0x2f, 0x79, 0x89, 0xd0, 0x26, 0x29, 0xfa, 0x15, 0x40,
	0x38, 0x6f, 0xd4, 0x14, 0xa8, 0x0c, 0xff, 0x57, 0x4e, 0x87, 0xd0, 0xa1, 0xdc, 0xb8, 0xdc, 0x7a,
	0x8b, 0xbd, 0x61, 0x3f, 0xae, 0x56, 0x15, 0x5f, 0xac, 0x2a, 0xde, 0x45, 0xcc, 0x3f, 0xb2, 0xdc,
	0x71, 0x5a, 0x33, 0xc9, 0x1d, 0x58, 0x7d, 0xa5, 0x35, 0xea, 0xb0, 0xbd, 0x1d, 0x0c, 0xba, 0xb4,
	0x7a, 0x88, 0x7e, 0xb4, 0xe1, 0xf1, 0xac, 0x7e, 0xdd, 0x9f, 0xca, 0x46, 0x53, 0x63, 0xb9, 0xdc,
	0x43, 0x75, 0x22, 0x32, 0x57, 0xb5, 0x4c, 0x22, 0xf8, 0xbf, 0x76, 0xaa, 0x0f, 0x98, 0xe4, 0x61,
	0xe0, 0xd5, 0x1a, 0x31, 0x72, 0x00, 0x6b, 0x6c, 0x22, 0x85, 0x12, 0xc6, 0x6a, 0x66, 0x51, 0xd7,
	0x2e, 0x07, 0x0b, 0x3a, 0x3e, 0x32, 0x5c, 0x37, 0x8a, 0xd0, 0x66, 0x3a, 0x79, 0x0e, 0xab, 0xce,
	0x70, 0x6d, 0xc2, 0xb6, 0x9f, 0xdc, 0xf2, 0x3a, 0x55, 0x1a, 0xd9, 0x02, 0x48, 0x9d, 0xb1, 0x28,
	0x5f, 0x32, 0xcb, 0xc2, 0x15, 0xef, 0xf8, 0x5a, 0x84, 0xec, 0x01, 0x14, 0x6e, 0x9c, 0x8b, 0xf4,
	0x2d, 0x9f, 0x9a, 0x70, 0xd5, 0x17, 0xd9, 0x59, 0x50, 0x64, 0x34, 0x7a, 0xfd, 0xe1, 0x82, 0x4b,
	0xaf, 0xa5, 0x91, 0x4f, 0x40, 0x72, 0xa1, 0xdc, 0xb7, 0x86, 0x83, 0xb0, 0xe3, 0x3b, 0x7f, 0xb4,
	0x40, 0xec, 0xdd, 0x5c, 0x02, 0xbd, 0x41, 0x24, 0xfa, 0x1d, 0xc0, 0xad, 0xd9, 0x25, 0x11, 0x02,
	0x2b, 0xea, 0x6a, 0x01, 0xfe, 0x3f, 0x59, 0x87, 0x96, 0x98, 0xf8, 0x69, 0x77, 0x69, 0x4b, 0x4c,
	0xc8, 0x08, 0x5a, 0x68, 0xfc, 0xc2, 0x7b, 0xc3, 0xbd, 0x25, 0xdf, 0xb7, 0xbf, 0x6d, 0x9f, 0xb6,
	0xd0, 0x90, 0x7b, 0xd0, 0xcd, 0x34, 0xba, 0xc2, 0xaf, 0xbf, 0x1a, 0xe6, 0x55, 0x80, 0xec, 0x40,
	0xc7, 0x58, 0x66, 0x5d, 0x39, 0xc7, 0xb2, 0x6c, 0xcf, 0x97, 0x1d, 0xf9, 0x10, 0xad, 0x21, 0x72,
	0x1f, 0x56, 0x2c, 0xcb, 0x4c, 0x3d, 0x9d, 0xae, 0xa7, 0x1c, 0xb2, 0xcc, 0x50, 0x1f, 0x1e, 0x7e,
	0x0f, 0x60, 0x63, 0xd6, 0xd6, 0x8b, 0xd2, 0x34, 0x39, 0x83, 0xce, 0x1b, 0x75, 0x8e, 0x67, 0x9c,
	0xc4, 0xcb, 0x9e, 0x4f, 0xf5, 0xcd, 0xe8, 0x27, 0x4b, 0xf3, 0xab, 0xd3, 0x8d, 0xfe, 0xdb, 0x7d,
	0xf2, 0x39, 0xce, 0x84, 0x3d, 0x75, 0xe3, 0x92, 0x9c, 0x48, 0x91, 0x6a, 0x34, 0x78, 0x62, 0x13,
	0x89, 0x69, 0xa2, 0x8b, 0x34, 0xb9, 0x14, 0x4b, 0x6a, 0xb1, 0x71, 0xc7, 0xdf, 0xdf, 0xd3, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x9a, 0xc0, 0x29, 0x94, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BareMetalMachineAgentClient is the client API for BareMetalMachineAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BareMetalMachineAgentClient interface {
	Invoke(ctx context.Context, in *BareMetalMachineRequest, opts ...grpc.CallOption) (*BareMetalMachineResponse, error)
}

type bareMetalMachineAgentClient struct {
	cc *grpc.ClientConn
}

func NewBareMetalMachineAgentClient(cc *grpc.ClientConn) BareMetalMachineAgentClient {
	return &bareMetalMachineAgentClient{cc}
}

func (c *bareMetalMachineAgentClient) Invoke(ctx context.Context, in *BareMetalMachineRequest, opts ...grpc.CallOption) (*BareMetalMachineResponse, error) {
	out := new(BareMetalMachineResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.compute.BareMetalMachineAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BareMetalMachineAgentServer is the server API for BareMetalMachineAgent service.
type BareMetalMachineAgentServer interface {
	Invoke(context.Context, *BareMetalMachineRequest) (*BareMetalMachineResponse, error)
}

// UnimplementedBareMetalMachineAgentServer can be embedded to have forward compatible implementations.
type UnimplementedBareMetalMachineAgentServer struct {
}

func (*UnimplementedBareMetalMachineAgentServer) Invoke(ctx context.Context, req *BareMetalMachineRequest) (*BareMetalMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterBareMetalMachineAgentServer(s *grpc.Server, srv BareMetalMachineAgentServer) {
	s.RegisterService(&_BareMetalMachineAgent_serviceDesc, srv)
}

func _BareMetalMachineAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BareMetalMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BareMetalMachineAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.compute.BareMetalMachineAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BareMetalMachineAgentServer).Invoke(ctx, req.(*BareMetalMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BareMetalMachineAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.nodeagent.compute.BareMetalMachineAgent",
	HandlerType: (*BareMetalMachineAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _BareMetalMachineAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_nodeagent_baremetalmachine.proto",
}
